baseURL = "http://joe-towing.com/"
languageCode = "en-us"
title = "Joe Towing Services"
theme = "hugo-simple-business"
author = "Joe Towing"
disableKinds = ["taxonomy", "taxonomyTerm"]
[services]
  [services.googleAnalytics]
    ID = "G-FT3ZG6PRNY"
[params]
  Description = "Towing and recovery, winch out, and roadside assistance for Western Washington"
  LocationsDescription = "We provide towing services for the following cities and their surrounding areas in Washington State:"
  Locations = [
    "Olympia",
    "Tacoma",
    "Gig Harbor",
    "Puyallup",
    "Kent",
    "Lakewood",
    "Seattle",
    "Lynnwood",
    "Everette",
    "Marysville",
    "Bremerton"
  ]
  LogoPath = ""
  Phone = "1-253-292-7032"
  Email = "joetowing21@gmail.com"
  Hours = [
    "Monday: 9:00AM-9:00PM",
    "Tuesday: 9:00AM-9:00PM",
    "Wednesday: 9:00AM-9:00PM",
    "Thursday: 9:00AM-9:00PM",
    "Friday: 9:00AM-9:00PM",
    "Saturday: 9:00AM-9:00PM",
    "Sunday: CLOSED",
  ]
  ServicesTitle = "Towing and Roadside Assistance"
  Services = [
    "Towing and Recovery",
    "Fuel Delivery",
    "Tire Changes",
    "Winch Out",
    "Lock Outs",
    "Jump Starts"
  ]
  GoogleTag = "AW-1006853375"
